### ISSUE TITLE
Teste migração OpenSearch

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario-data-processing#34]
Realizar um teste de migração do ElasticSearch(ES) para o OpenSearch(OS)

Algumas tarefas
- [ ] Criar um ambiente de teste local que roda em Linux
- [ ] Tentar trocar o ES pelo OS sem alterações no código

**Importante**: essa tarefa ainda precisa ser mais detalhada. ;)

**Comment by tigreped** [comment]
Tentando detalhar mais as tarefas:

[ ]  Disponibilização de duplicata do servidor e índices do ElasticSearch no droplet da DigitalOcean
[ ]  Instalação do OpenSearch 2.9.0 na máquina
[ ]  Migração de configurações relevantes, como configurações de índices, mappings, settings, e quaisquer outras personalizações específicas do ES para o OS.
[ ]  Migração dos Dados, utlizando [snapshot](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/) ou usando o plugin de exportação de dados do ElasticSearch e o plugin de importação do OpenSearch usando [Logstash](https://github.com/opensearch-project/logstash-output-opensearch#configuration-for-logstash-output-opensearch-plugin)
[ ]  Teste dos dados carregados, comparando a instância ES com a instância OS, quantidade de documentos por índice, estrutura dos índices, etc
[ ]  Instalação de uma instância do querido-diario-api na máquina, com adaptação do código para interação com os dados através da biblioteca python para OpenSearch
[ ]  Teste dos endpoints da API, comparando os resultados trazidos na máquina de produção ES com a máquina de testes OS

**Comment by tigreped** [comment]
- [x] Disponibilização de duplicata do servidor e índices do ElasticSearch no droplet da DigitalOcean
- [x] Instalação do OpenSearch 2.9.0 na máquina
- [x] Instalação do OpenSearch 1.3.12 na máquina (para compatibilidade com o ES atual (v7.17.11))

**Em andamento:**
- [x] Migração dos dados utlizando [snapshot](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/snapshot-restore/). Inicialmente houve conflite de versões entre o ES (v7.17.11) e o OS (v2.X) sendo necessário fazer um downgrade do OS para a versão 1.3.12. A geração do snapshot usando o ES aparenta ter sido realizada com sucesso, entretanto a detecção do snapshot pelo OS não teve sucesso por problema de falta de compatibilidade.

**A fazer:**
- [ ] Teste dos dados carregados, comparando a instância ES com a instância OS, quantidade de documentos por índice, estrutura dos índices, etc
- [ ] Instalação de uma instância do querido-diario-api na máquina, com adaptação do código para interação com os dados através da biblioteca python para OpenSearch
- [ ] Teste dos endpoints da API, comparando os resultados trazidos na máquina de produção ES com a máquina de testes OS

**Comment by tigreped** [comment]
Carga dos dados concluída com sucesso utilizando elasticdump e exportação para arquivos, com um filtro na consulta para retornar os dados em fatias por estado e por data de raspagem. Arquivos movidos entre as máquinas utilizando scp e carregados de volta dos arquivos para o opensearch com sucesso. Primeiro as configurações e mapeamentos dos índices e depois os dados.

Uma instância do querido-diario-api está instalada e configurada corretamente para se conectar à instância OpenSearch que agora está rodando na porta 9200, no lugar do ElasticSearch. Já foi substituída com sucesso a biblioteca python que estava sendo utilizada nas interfaces de conexão com o motor de busca para a biblioteca opensearch-py da OpenSearch, falta fazer uma epecificação da versão dela no requirements.txt

Em breve organizo a branch para retirar alterações sensíveis de servidor que são apenas para a execução na instância e faço o push das alterações para podermos intergrar a mudança quando o componente querido-diario com os raspadores também estiver atualizado para interagir com o opensearch ao invés do elasticsearch.

**Comment by jvanz** [comment]
Opensearch já está em uso.
