### ISSUE TITLE
Replicar o segmentador de diários da Associação AMA do exoonero

### ISSUE THREAD

**Issue by Jefersonalves** [okfn-brasil/querido-diario-data-processing#40]
Essa Issue faz parte de um esforço para segmentar os diários dos municípios quando estes são publicados em um diário centralizador de uma Associação de municípios.
Um estudo de caso foi conduzido no repositório https://github.com/exoonero/extrator para o caso da AMA.
Nesse contexto, essa issue tem o objetivo de:
- [ ] selecionar os trechos de código do exoonero que fazem a segmentação dos diários e replicar
- [ ] acomodar o código replicado da melhor maneira considerando a estrutura atual do data processing

**Comment by ogecece** [comment]
Fechando essa issue pois o conteúdo final foi integrado em #64
