### ISSUE TITLE
[Prototipo funcional] data-processing e Associação AMA exoonero

### ISSUE THREAD

**Issue by Winzen** [okfn-brasil/querido-diario-data-processing#43]
Estarei abrindo essa Issue para poder apresentar e facilitar o acompanhamento do protótipo já funcional do data-processing e o exoonero.

Essa não é uma versão final e busca passar por varias revisões. 
O protótipo foca em sondar possíveis problemas, dar molde para uma versão final e limpa.
Ele já consegui segmentar os diários da AMA e chegar ao ponto final do processamento dos diários .

# Objetivos inicias e principais
- [x] Segmentar Diarios dentro do storage(Separados por id e suas datas).
- [x] Fazer o registros dos metadados dos diarios segmetados.
- [x] Fazer a indexação dos diarios segmetados com elasticsearch.
# Passos a serem adicionados e melhorados.
- [x] Criar verificador no registro dos metadados para evitar duplicados. ➡️ [Parte a modificar](https://github.com/Winzen/querido-diario-data-processing/blob/prototype/tasks/gazette_text_extraction.py#L272)
- [ ] Verificar melhor formar de tratar duplicadas.(Naturalmente o projeto já evita que elas sejam adicionadas. Porém, ele levanta um erro e para o processo)
- [ ] Colocar um tratador de erro caso ele não consiga pegar territory_id. ➡️ [Parte a modificar](https://github.com/Winzen/querido-diario-data-processing/blob/prototype/tasks/get_territorie_info.py#L5)
- [x] Verificar porque aparamente ele não esta conseguindo processar todos os pdfs de uma vez
- [ ] Criar `self.url` corretamente usando o `get_file_endpoint()`.➡️ [Parte a modificar](https://github.com/Winzen/querido-diario-data-processing/blob/prototype/tasks/diario_municipal.py#L72)
- [ ] Atualização da documentação.
  - [ ] Como conectar querido-diario e data-processing(lembrar de falar do csv)
  - [ ] Configurar ambiente no windons(wsl)
- [ ] Verificar se está com um consumo excessivo de ram

**Comment by ogecece** [comment]
Fechando essa issue pois o conteúdo final foi integrado em #64
