### ISSUE TITLE
Build do servidor Apache Tika está quebrado

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-data-processing#73]
Ao realizar o build localmente do servidor Apache Tika (`make build` ou `make build-tika-server`) e levantá-lo (`make setup` ou `make create-pod && make apache-tika-server`) os logs do container apresentam apenas a mensagem de erro: `Error: Invalid or corrupt jarfile /tika-server.jar`.

Por enquanto, para levantar um Tika localmente devemos executar `podman pull ghcr.io/okfn-brasil/querido-diario-apache-tika-server:latest` ao invés do build local, pois a imagem criada para produção está funcional.

**Comment by ogecece** [comment]
A imagem tika de produção teve seu último build em 29/11/2022: https://github.com/orgs/okfn-brasil/packages/container/package/querido-diario-apache-tika-server

**Comment by jvanz** [comment]
Acredito que o binário do Apache Tika está corrompido. Eu baixei ele localmente na minha estação de trabalho e ainda está dando o mesmo problema:

```console
$ java -jar tika-server.jar
Error: Invalid or corrupt jarfile tika-server.jar
```

Acredito que devemos atualizar o nosso servidor do Tika para 2.9.1. O branch `1.x.x` não é mais mantido.
